# EX4 Text Analysis

Points
- Q1, 1P
- Q2, 2P
- Q3, 4P
- Q4, 3P

In [ ]:
# 必要なモジュールのimport
import numpy as np
import pandas as pd

## Q1
Given any two vectors in an $n$-dimensional vector space, $ \vec{x}=(x_1,x_2,... ,x_n)$, $\vec{y}=(y_1,y_2,... ,y_n)$, the cos similarity, $cos( \vec{x}, \vec{y})$, between these vectors is defined as follows:

$cos( \vec{x}, \vec{y}) =  \frac{\vec{x}\cdot \vec{y}}{\|x\|_2\|y\|_2}=\frac{\Sigma^{n}_{i=1}{x_{i}y_{i}}}{\sqrt{\Sigma^{n}_{i=1}x_{i}^{2}}\sqrt{\Sigma^{n}_{i=1}y_{i}^{2}}}$.

Complete the `cos_sim` function that takes the input vectors $\vec{x}$ and $\vec{y}$ as `NumPy` arrays and returns the cos similarity between these vectors.

In [ ]:
def cos_sim(vec1, vec2):
  return np.dot(vec1,vec2)/(np.linalg.norm(vec1)*np.linalg.norm(vec2))

Once the `cos_sim()` function is complete, run the following cell to see how it works.

In [ ]:
print(round(cos_sim(np.array([1,0,1]), np.array([1,1,1])), 2))
print(round(cos_sim(np.array([1,1,1]), np.array([1,1,1])), 2))
print(round(cos_sim(np.array([-1,-1,-1]), np.array([1,1,1])), 2))

0.82
1.0
-1.0


Make sure that your function returns `0.82`, `1.0`, `-1.0` respectively.

## Q2
The following "course_list.csv" file contains text data with a lecture title in each line. 

```Python
## course_list.csvファイル
...
数理科学基礎
物性化学
政治Ⅰ
身体運動・健康科学実習Ⅰ（ﾒﾃﾞｨｶﾙｹｱ1）
スペイン語テクスト分析Ⅰ
英語二列Ｗ（ALESS）
応用倫理学
...
```

In the following, you are going to implement the codes to create a vector representing a lecture and calculate the similarity between the lectures.

In [ ]:
# Colaboratoryでは以下を実行して必要なファイルをダウンロード
!wget https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/course_list.csv

--2022-11-05 13:27:09--  https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/course_list.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27388 (27K) [text/plain]
Saving to: ‘course_list.csv’

course_list.csv     100%[===================>]  26.75K  --.-KB/s    in 0s      

2022-11-05 13:27:09 (86.6 MB/s) - ‘course_list.csv’ saved [27388/27388]



### Q2.1
Complete the `create_list` function that reads each row in order given the `file` and returns a list with each row as its element. 

The created list is received in the variable `courses`. 

**The index of `courses` list is regarded as its corresponding lecture's ID.**

In [ ]:
def create_list(file):
  return pd.read_csv(file, header=None, encoding="utf-8").values.flatten().tolist()

Once the `create_list` function is complete, run the following cell. Your function should return a list with length `552`.

ID (its index of `courses` list) of a lecture "計算機プログラミング" should be `198`.

In [ ]:
courses = create_list('course_list.csv')
print(len(courses))
print(courses.index('計算機プログラミング'))

552
198


The following"keyword_list.csv" file contains one word in each line.

```Python
## keyword_list.csvファイル
...
外国語
日本語
力学
身体運動
微分積分学
ロシア語
熱力学
線型代数学
イタリア語
物性
...
```

In the following, we read the "keywor_list.csv" file and create a list with each line as its element. 

The created list is received in the variable `vocab`. 


**The index of `vocab` list is regarded as its corresponding word's ID.**


In [ ]:
# Colaboratoryでは以下を実行して必要なファイルをダウンロード
!wget https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/keyword_list.csv

--2022-11-05 13:27:10--  https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/keyword_list.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2513 (2.5K) [text/plain]
Saving to: ‘keyword_list.csv.1’

keyword_list.csv.1  100%[===================>]   2.45K  --.-KB/s    in 0s      

2022-11-05 13:27:10 (32.9 MB/s) - ‘keyword_list.csv.1’ saved [2513/2513]



Run the following cell. Your function should return a list with length `243`.

ID (its index of `vocab`list) of a word "プログラミング" should be `145`.


In [ ]:
vocab = create_list('keyword_list.csv')
print(len(vocab))
print(vocab.index('プログラミング'))
print(vocab.index('英語'))

243
145
0


### Q2.2
Complete the `count_df` function that takes the `courses` and `vocab` lists and return a dictionary with the word ID (the index of that word in `vocab`) as key and Document Frequency (DF) of that word as value.
Note that DF of a word is the number of lectures containing that word in its title. **Even if a word appears more than once in a lecture title, it is counted once**.


In [ ]:
def count_df(courses, vocab):
  dic={}
  for i in range(len(vocab)):
    for c in courses:
      if vocab[i] in c:
        if i in dic:
          dic[i] +=1
        else:
          dic[i]= 1
  return dic

Once the `count_df` function is complete, run the following code. Your function should return a dictionary with lenght `243`. And DF of a word "プログラミング"（its ID is `145`）should be `2`.

In [ ]:
df = count_df(courses, vocab)
print(len(df))
print(vocab.index('プログラミング'), df[vocab.index('プログラミング')])
print(vocab.index('英語'), df[vocab.index('英語')])

243
145 2
0 12


## Q3
### Q3.1
Consider a vector to represent a lecture, whose dimension is each word in `vocab`. The vector length is equal to the length of `vocab`, and the `i`th element of the vector is `1` if when the word `vocab[i]` is included in the lecture title, and `0` otherwise.

Complete the `lec_word_matrix` function that takes the `courses` and `vocab` lists and returns a `NumPy` matrix with the vector of each lecture in `courses` as its row and each word in `vocab` as its column. In the returned matrix (lecture-word matrix), if a lecture title (row) contains a word (column), then its corresponding element should be 1.


In [ ]:
def lec_word_matrix(courses, vocab):
  ### Arguments：
  # courses: lecture list
  # vocab: word list
  mat = np.zeros((len(courses), len(vocab)))
  for i in range(len(vocab)):
      for j in range(len(courses)):
        if vocab[i] in courses[j]:
            mat[j][i] = 1
  return mat

Once the `lec_word_matrix` function is complete, run the following cell. Your function should return a matrix with a shape `(552, 243)` and the sum of its element values should be `2287`.

In [ ]:
print(lec_word_matrix(courses, vocab).shape)
print(np.sum(lec_word_matrix(courses, vocab)))

(552, 243)
2287.0


### Q3.2
Complete the `lec_word_tf_matrix` to return a matrix where each element of the lecture-word matrix in Q3.1 is represented by the number of times the lecture title contains the word (TF: Term Frequency), rather than 1 or 0.


In [ ]:
def lec_word_tf_matrix(courses, vocab):
  ### Arguments：
  # courses: lecture list
  # vocab: word list
  mat = np.zeros((len(courses), len(vocab)))
  for i in range(len(vocab)):
      for j in range(len(courses)):
        if vocab[i] in courses[j]:
            mat[j][i] = courses[j].count(vocab[i])
  return mat

Once the `lec_word_tf_matrix` function is complete, run the following cell. Your function should return a matrix whose the sum of its element values is `2366`.

For example, a lecture 「自然科学ゼミナール（情報科学）」 contains 「科学」 twice in its title. Therefore, its correspoinding matrix element should be 2.

In [ ]:
print(np.sum(lec_word_tf_matrix(courses, vocab)))
print(lec_word_tf_matrix(courses, vocab)[courses.index('自然科学ゼミナール（情報科学）'), vocab.index('科学')])

2366.0
2.0


### Q3.3
Complete the `lec_word_tfidf_matrix` function that returns a matrix whose elements are TFIDF values obtained by multiplying each element of the lecture-word matrix in Q3.2 ($TF_{ij}$ for word `j` in lecture `i`) by the IDF value of that word.

Here, the TFIDF values for lecture `i` and word `j` are defined as follows:

```Python
TFIDF=TF_ij*log(the number of lectures/DF for word j)=TF_ij*log(len(courses)/df[j])
```
You may use `np.log()`.

In [ ]:
def lec_word_tfidf_matrix(courses, vocab, df):
  ### Arguments：
  # courses: lecture list
  # vocab: word list
  # df: DF dictionary
  mat = np.zeros((len(courses), len(vocab))) 
  for j in range(len(vocab)):
      for i in range(len(courses)):
        if vocab[j] in courses[i]:
            mat[i][j] = courses[i].count(vocab[j])*np.log(len(courses)/df[j])
  return mat

Once the `lec_word_tfidf_matrix` function is complete, run the following cell. Your function should return a matrix whose the integer part of the sum of its element values is `7274`.

A lecture 「自然科学ゼミナール（情報科学）」 contains 「科学」 twice in its title and DF for 「科学」 is 75. Therefore, its corresponding matrix element should be $2*log(552/75)\simeq3.99$.

In [ ]:
tfidf_mat = lec_word_tfidf_matrix(courses, vocab, df)
print(int(np.sum(tfidf_mat)))
print(df[vocab.index('科学')], tfidf_mat[courses.index('自然科学ゼミナール（情報科学）'), vocab.index('科学')])

7274
75 3.9921198654815697


## Q4
Complete the `find_similar_course` function that calculates the similarity of the input lecture to all other lectures based on cos similarity and returns a dictionary with the titles of similar lectures as its keys and their similarity as values. You may use the function in Q1 to calculate cos similarity.

Note that the input lecture and lectures with similarity of 0 should not be included in the dictionary. 



In [ ]:
def find_similar_course(target, tfidf_mat, courses):
  ### Arguments：
  # target:  ID of a input lecture
  # tfidf_mat: matrix created in Q3.3
  # courses: lecture list
  dic = {courses[i] : cos_sim(tfidf_mat[target],tfidf_mat[i]) for i in range(len(courses)) if not (target == i or cos_sim(tfidf_mat[target],tfidf_mat[i])==0) }
  return dic

In [ ]:
len(cos_sim(tfidf_mat,tfidf_mat[152]))

552

Once the `find_similar_course` function is complete, run the following cell.

The top similar lectures to the input lecture `自然科学ゼミナール（情報科学）` are `自然科学ゼミナール（生命科学）、生物情報科学、自然科学ゼミナール（数理科学）、自然現象とモデル、人類科学、...`.

The number of similar lectures should be `230`.

In [ ]:
tfidf_mat = lec_word_tfidf_matrix(courses, vocab, df)
title="自然科学ゼミナール（情報科学）" # 入力の授業名
results=find_similar_course(courses.index(title), tfidf_mat, courses) # 類似授業の辞書を受け取る
print(len(results)) # 類似授業の数
ranking = pd.DataFrame(list(results.items()), columns=['title', "similarity"]) # 類似度が上位の授業を表示
ranking.sort_values(by='similarity', ascending=False).head(10)

230


title  similarity
70                             自然科学ゼミナール（生命科学）    0.644874
88                                      生物情報科学    0.631863
68                             自然科学ゼミナール（数理科学）    0.622156
196                                   自然現象とモデル    0.399247
67                                        人類科学    0.387201
87                                        食の科学    0.387201
65                                      天然物の科学    0.387201
5                                           情報    0.332018
169   全学体験ゼミナール　(都市の緑のインタープリター養成－子どもに伝える自然体験－)    0.308337
120  全学自由研究ゼミナール　(ミュオグラフィ科学/Muography Science)    0.281423

## Code Testing


In [ ]:
# Run this cell first
!pip install prog_edu_assistant_tools
import re
import sys
import jinja2
from IPython.core import display
from google.colab import _message as google_message
from prog_edu_assistant_tools.magics import report, autotest, CaptureOutput
from prog_edu_assistant_tools.check import Check

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 7.4 MB/s 


## Q1

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q1')

## Q2.1

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q2_1')

## Q2.2

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q2_2')

## Q3.1

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q3_1')

## Q3.2

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q3_2')

## Q3.3

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q3_3')

## Q4

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q4')